name: Java CI/CD with Maven

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build with Maven
        run: mvn clean install

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-action-artifact
          path: target/*.jar

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: github-action-artifact

      - name: Run unit tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: github-action-artifact

      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            echo "Connected to EC2 instance"
            sudo docker stop $(sudo docker ps -aq) || true
            sudo docker rm $(sudo docker ps -aq) || true    
            sudo docker pull vm2124/spring-boot-github-action-demo
            sudo docker run -d -p 8080:8080 vm2124/spring-boot-github-action-demo
